// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Used only by the Prisma CLI (migrate / studio / db pull). Prefer the
    // session-mode pooler (DIRECT_URL, port 5432) since the transaction-mode
    // pooler can't run migrations. Runtime uses the adapter in src/lib/prisma.ts
    // with DATABASE_URL (transaction pooler, port 6543).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
